import type { Config } from "tailwindcss";

// Merge this `extend` block into your existing shadcn tailwind.config.ts
// (keep shadcn's own color tokens like `border`, `input`, `ring`, `background`,
// `foreground`, `card`, `popover`, `primary`, `secondary`, `muted`, `accent`,
// `destructive` etc. — just add these extra Material-3-style tokens alongside them.)

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#d8e3fb",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#3322cc",
        "primary-container": "#2563eb",
        "inverse-primary": "#b4c5ff",
        "on-secondary-fixed": "#0f0069",
        tertiary: "#006241",
        "surface-bright": "#f9f9ff",
        "surface-variant": "#d8e3fb",
        "on-primary": "#ffffff",
        "tertiary-container": "#007d55",
        "tertiary-fixed-dim": "#77d9aa",
        "on-tertiary": "#ffffff",
        error: "#ba1a1a",
        surface: "#f9f9ff",
        "physics-bg": "#f5f3ff",
        "primary-fixed": "#dbe1ff",
        "on-primary-container": "#eeefff",
        outline: "#737686",
        "tertiary-fixed": "#93f6c5",
        "math-bg": "#eff6ff",
        "inverse-on-surface": "#ecf1ff",
        "on-tertiary-container": "#bdffda",
        "background-alt": "#f9f9ff",
        primary: "#004ac6",
        "primary-fixed-dim": "#b4c5ff",
        "on-surface-variant": "#434655",
        "chemistry-bg": "#ecfdf5",
        "secondary-container": "#655dfb",
        "on-background": "#111c2d",
        "outline-variant": "#c3c6d7",
        "otp-inactive": "#e2e8f0",
        "on-primary-fixed-variant": "#003ea8",
        "surface-tint": "#0053db",
        "surface-container-low": "#f0f3ff",
        "surface-container": "#e7eeff",
        "on-surface": "#111c2d",
        "secondary-fixed": "#e2dfff",
        "on-secondary-container": "#fffbff",
        "secondary-fixed-dim": "#c3c0ff",
        "on-error-container": "#93000a",
        background: "#f9f9ff",
        "on-secondary": "#ffffff",
        "surface-container-high": "#dee8ff",
        "on-error": "#ffffff",
        "on-primary-fixed": "#00174b",
        secondary: "#4b41e1",
        "inverse-surface": "#263143",
        "on-tertiary-fixed": "#002113",
        "surface-card": "#ffffff",
        "surface-dim": "#cfdaf2",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#005236",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        lg: "40px",
        "margin-mobile": "16px",
        xs: "8px",
        base: "4px",
        md: "24px",
        sm: "16px",
        xl: "64px",
        "gutter-mobile": "16px",
        "max-width-content": "800px",
      },
      maxWidth: {
        content: "800px",
      },
      fontFamily: {
        "label-bold": ["var(--font-inter)"],
        "display-lg-mobile": ["var(--font-inter)"],
        "math-display": ["var(--font-source-serif)"],
        "display-lg": ["var(--font-inter)"],
        "body-lg": ["var(--font-inter)"],
        "headline-sm": ["var(--font-inter)"],
        "headline-md": ["var(--font-inter)"],
        "label-sm": ["var(--font-inter)"],
        "body-md": ["var(--font-inter)"],
      },
      fontSize: {
        "label-bold": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "math-display": ["20px", { lineHeight: "32px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
      boxShadow: {
        ambient: "0 20px 40px -15px rgba(0, 0, 0, 0.05)",
      },
    },
  },
  plugins: [],
};

export default config;
